model:
  name: UNet2D
  in_channels: 1
  out_channels: 1
  layer_order: bcr
  num_groups: 2
  f_maps: [16, 32, 64]
  final_sigmoid: true
  is_segmentation: true
trainer:
  checkpoint_dir: /n/scratch/users/a/ajn16/cspot_new/model
  resume: null
  pre_trained: null
  validate_after_iters: 250
  log_after_iters: 250
  max_num_epochs: 100
  max_num_iterations: 150000
  eval_score_higher_is_better: True
optimizer:
  learning_rate: 0.0005
  weight_decay: 0.002
loss:
  name: WeightedCrossEntropyLoss
  skip_last_target: false
eval_metric:
  name: MeanIoU
  use_last_target: true
  metric: 'ap'
lr_scheduler:
  name: ReduceLROnPlateau
loaders:
  batch_size: 16
  num_workers: 8
  raw_internal_path: /raw
  label_internal_path: /label
  train:
    file_paths:
      - /n/scratch/users/a/ajn16/cspot_new/training/CD3e/train
    slice_builder:
      name: SliceBuilder
      patch_shape: [1, 64, 64]
      stride_shape: [1, 64, 64]

    transformer:
      raw:
        - name: LocalNorm
          execution_probability: 0.4
        - name: Standardize
        - name: RandomFlip
        - name: RandomRotate90
        - name: ToTensor
          expand_dims: true
      label:
        - name: RandomFlip
        - name: RandomRotate90
        - name: ToTensor
          expand_dims: true
  val:
    file_paths:
      - /n/scratch/users/a/ajn16/cspot_new/training/CD3e/validation
    slice_builder:
      name: SliceBuilder
      patch_shape: [1, 64, 64]
      stride_shape: [1, 64, 64]

    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: true
      label:
        - name: Relabel
        - name: ToTensor
          expand_dims: true
